### PR TITLE
fix security issue reported by white source scan

### PR DESCRIPTION
**Pull request by pugangxa**
See https://github.com/open-policy-agent/opa/security/advisories/GHSA-hcw3-j74m-qc58

### CODE REVIEW

**Comment by roytman** [comment]
Hi Gang, thanks for the PR, but you cannot just update OPA, because newer OPA versions depends on a new version of `opentelemetry` which is incompatible with previous versions used by other fybrik packages.

P.S. when you update go.mod you have to update go.sum by running `go mod tidy`

**Comment by pugangxa** [comment]
> Hi Gang, thanks for the PR, but you cannot just update OPA, because newer OPA versions depends on a new version of `opentelemetry` which is incompatible with previous versions used by other fybrik packages.
> 
> P.S. when you update go.mod you have to update go.sum by running `go mod tidy`

Yes, you are right, when I run `go mod tidy` there's error about `opentelemetry`, seems need update that too.

**Comment by pugangxa** [comment]
Took further look about this
```
(base) ➜  fybrik git:(fix-cve-opa) ✗ go mod tidy
go: finding module for package go.opentelemetry.io/otel/metric/registry
fybrik.io/fybrik/pkg/taxonomy/validate imports
	k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/validation imports
	k8s.io/apiserver/pkg/util/webhook imports
	k8s.io/component-base/traces imports
	go.opentelemetry.io/otel/exporters/otlp imports
	go.opentelemetry.io/otel/sdk/metric/controller/basic imports
	go.opentelemetry.io/otel/metric/registry: module go.opentelemetry.io/otel/metric@latest found (v0.28.0), but does not contain package go.opentelemetry.io/otel/metric/registry
```
But seems even the newest https://github.com/kubernetes/component-base/blob/master/go.mod still use old version, so maybe wait for them to upgrade.

**Comment by pugangxa** [comment]
Logged https://github.com/kubernetes/component-base/issues/5 and will need them to fix firstly.

**Comment by roytman** [comment]
Blocked by https://github.com/kubernetes/kubernetes/issues/106536 and

**Comment by roytman** [comment]
Done by https://github.com/fybrik/fybrik/pull/1813

**Pull request closed without merging**
