### PR TITLE
Mac support for or_tools

### PR DESCRIPTION
**Pull request by zivnevo**
Also upgrading to OR Tools version 9.5

Should solve some of the issues in #1525

### CODE REVIEW

**Review by shlomitk1 — COMMENTED** [review]
Currently, the optimizer image is hard-coded to **image: "ghcr.io/fybrik/optimizer:0.0.1"** which was built quite a while ago. In order to proper test the Dockerfile, the following is required:
- replace solver.image with "optimizer" for all charts/fybrik/values*.yaml 
- add docker-build for optimizer in Makefile (where manager is built)
- add docker-push for optimizer in the git push action

**Comment by zivnevo** [comment]
> Currently, the optimizer image is hard-coded to **image: "ghcr.io/fybrik/optimizer:0.0.1"** which was built quite a while ago. In order to proper test the Dockerfile, the following is required:
> 
>     * replace solver.image with "optimizer" for all charts/fybrik/values*.yaml
> 
>     * add docker-build for optimizer in Makefile (where manager is built)
> 
>     * add docker-push for optimizer in the git push action

I'm not sure I understand which tests take which image from which location. In practice, `Tekton Tests` passed only after I modified the Dockerfile to run the solver install script.
How about a new issue for the changes you proposed?

**Comment by shlomitk1** [comment]
> 
> I'm not sure I understand which tests take which image from which location. In practice, `Tekton Tests` passed only after I modified the Dockerfile to run the solver install script. How about a new issue for the changes you proposed?

Tekton tests do not use the solver image, they use the local installation instead. I believe that they pass because you changed the install script. The changes to Dockerfile do not have any effect at all because "make docker-build docker-push" is never called for the optimizer. 
My concern is that your changes to Dockerfile have not been tested because of the hard-coded old image that was created in March. If you remove Dockerfile and Makefile from this PR, it's OK to have it merged.

**Review by shlomitk1 — APPROVED** [review]

**Pull request merged**
