### PR TITLE
Bug fix

### PR DESCRIPTION
**Pull request by shlomitk1**
Signed-off-by: Shlomit Koyfman <shlomitk@il.ibm.com>
Fixes https://github.com/fybrik/fybrik/issues/1718
This PR does not assume a specific field inside a connection interface but rather scans all string fields recursively to resolve templated values.

### CODE REVIEW

**Comment by roytman** [comment]
I checked the Notebook read scenario when arrow-flight module definition is in the module.yaml

```yaml
apiVersion: app.fybrik.io/v1beta1
kind: FybrikModule
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"app.fybrik.io/v1beta1","kind":"FybrikModule","metadata":{"annotations":{},"labels":{"name":"arrow-flight-module","version":"latest"},"name":"arrow-flight-module","namespace":"fybrik-system"},"spec":{"capabilities":[{"actions":[{"name":"RedactAction"},{"name":"RemoveAction"},{"name":"FilterAction"},{"name":"AgeFilterAction"}],"api":{"connection":{"fybrik-arrow-flight":{"hostname":"{{ .Release.Name }}.{{ .Release.Namespace }}","port":"80","scheme":"grpc"},"name":"fybrik-arrow-flight"}},"capability":"read","scope":"workload","supportedInterfaces":[{"source":{"dataformat":"parquet","protocol":"s3"}},{"source":{"dataformat":"csv","protocol":"s3"}},{"source":{"protocol":"fybrik-arrow-flight"}}]},{"actions":[{"name":"RedactAction"},{"name":"RemoveAction"},{"name":"FilterAction"},{"name":"AgeFilterAction"}],"api":{"connection":{"fybrik-arrow-flight":{"hostname":"{{ .Release.Name }}.{{ .Release.Namespace }}","port":"80","scheme":"grpc"},"name":"fybrik-arrow-flight"}},"capability":"write","scope":"workload","supportedInterfaces":[{"sink":{"dataformat":"parquet","protocol":"s3"}},{"sink":{"dataformat":"csv","protocol":"s3"}}]}],"chart":{"name":"ghcr.io/fybrik/arrow-flight-module-chart:0.8.0","values":{"image.tag":"0.8.0"}},"type":"service"}}
  creationTimestamp: "2022-09-16T16:57:48Z"
  generation: 2
  labels:
    name: arrow-flight-module
    version: latest
  name: arrow-flight-module
  namespace: fybrik-system
  resourceVersion: "9992"
  uid: db1be722-d8fb-48e6-8138-b55210fd3b19
spec:
  capabilities:
  - actions:
    - name: RedactAction
    - name: RemoveAction
    - name: FilterAction
    - name: AgeFilterAction
    api:
      connection:
        fybrik-arrow-flight:
          hostname: '{{ .Release.Name }}.{{ .Release.Namespace }}'
          port: "80"
          scheme: grpc
        name: fybrik
    capability: read
    scope: workload
    supportedInterfaces:
    - source:
        dataformat: parquet
        protocol: s3
    - source:
        dataformat: csv
        protocol: s3
    - source:
        protocol: fybrik-arrow-flight
  - actions:
    - name: RedactAction
    - name: RemoveAction
    - name: FilterAction
    - name: AgeFilterAction
    api:
      connection:
        fybrik-arrow-flight:
          hostname: '{{ .Release.Name }}.{{ .Release.Namespace }}'
          port: "80"
          scheme: grpc
        name: fybrik
    capability: write
    scope: workload
    supportedInterfaces:
    - sink:
        dataformat: parquet
        protocol: s3
    - sink:
        dataformat: csv
        protocol: s3
  chart:
    name: ghcr.io/fybrik/arrow-flight-module-chart:0.8.0
    values:
      image.tag: 0.8.0
  type: service
status:
  conditions:
  - observedGeneration: 2
    status: "True"
    type: Valid
```

The manager doesn't crash now, but its logs probably point mislead from the real issue
```
{"level":"trace","controller":"FybrikApplication","FybrikApplication":"fybrik-notebook-sample/my-notebook","app.fybrik.io/app-uuid":"01b1ad92-0f9f-48b5-ac47-cb5d6acf42a4","dataSetID":"fybrik-notebook-sample/paysim-csv","time":"2022-09-16T17:11:08Z","caller":"/Users/alexey/goWork/src/github.com/fybrik/fybrik/manager/controllers/app/select_modules.go:36","message":"Choose modules for dataset"}
{"level":"debug","controller":"FybrikApplication","FybrikApplication":"fybrik-notebook-sample/my-notebook","app.fybrik.io/app-uuid":"01b1ad92-0f9f-48b5-ac47-cb5d6acf42a4","time":"2022-09-16T17:11:08Z","caller":"/Users/alexey/goWork/src/github.com/fybrik/fybrik/manager/controllers/app/select_modules.go:221","message":"module arrow-flight-module does not support sink requirements for capability read"}
{"level":"error","controller":"FybrikApplication","FybrikApplication":"fybrik-notebook-sample/my-notebook","app.fybrik.io/app-uuid":"01b1ad92-0f9f-48b5-ac47-cb5d6acf42a4","dataSetID":"fybrik-notebook-sample/paysim-csv","time":"2022-09-16T17:11:08Z","caller":"/Users/alexey/goWork/src/github.com/fybrik/fybrik/manager/controllers/app/select_modules.go:41","message":"Deployed modules do not provide the functionality required to construct a data path"}
```

and finally 
```
{"level":"warn","controller":"FybrikApplication","FybrikApplication":"fybrik-notebook-sample/my-notebook","app.fybrik.io/app-uuid":"01b1ad92-0f9f-48b5-ac47-cb5d6acf42a4","action":"update","time":"2022-09-16T17:11:08Z","caller":"/Users/alexey/goWork/src/github.com/fybrik/fybrik/manager/controllers/app/fybrikapplication_controller.go:188","message":"Reconcile failed with errors"}
```
Should it provide more specific messages

**Comment by shlomitk1** [comment]
So the data path can not be constructed. Where is the problem here and how is it related to the original bug report?

**Comment by roytman** [comment]
> So the data path can not be constructed. Where is the problem here and how is it related to the original bug report?

The same problem - wrong module definition, mismatch between connection properties and its name
```yaml
        fybrik-arrow-flight:
          hostname: '{{ .Release.Name }}.{{ .Release.Namespace }}'
          port: "80"
          scheme: grpc
        name: fybrik
```

**Comment by shlomitk1** [comment]
Connection properties as well as connection names should be defined in the taxonomy. Were they defined in the taxonomy, the module validation would fail in the above case. So maybe the basic installation should come with the default taxonomy, I don't know. In any case it is not a bug - manager is not able to find a module that satisfies the expected protocol.

**Comment by roytman** [comment]
The original reported bug and as result manager crash was when there is mismatch of properties and name. Now manager does not crash, but my point, can we add log hits to help user to understand why module configuration and taxonomy are combined. so the module was not loaded and after that the manager is not able to find a module that satisfies the expected protocol. (Not founding a module is a result and not a source of the issue).

**Review by roytman — APPROVED** [review]

**Pull request merged**
