### PR TITLE
bump base image to ubi-minimal:8.6

### PR DESCRIPTION
**Pull request by roytman**
As one of the requirements from https://github.com/fybrik/fybrik/issues/1480, the base ubunty image was updated.

Signed-off-by: Alexey Roytman <roytman@il.ibm.com>

### CODE REVIEW

**Comment by revit13** [comment]
@roytman should the tag be `8.6` instead of `8.6-751`? this way we do not have to bump for minor version releases.

**Comment by roytman** [comment]
> @roytman should the tag be `8.6` instead of `8.6-751`? this way we do not have to bump for minor version releases.

good point, will fix

**Review by revit13 — APPROVED** [review]

**Pull request merged**
