### PR TITLE
Adding hyperlinks for missing request objects to REST APIs

### LINKED ISSUE #1544: katalog API documentation - missing links
katalog documentation doesn't include links to the structure of the parameters for the APIs.

Ex: getAssetInfo states that an object of type CreateAssetRequest should be sent as a parameter.  There is no link though to see what actually needs to be sent.

This is true for all of the APIs

Since the structure is defined in the taxonomy, mention of this should be made.

### PR DESCRIPTION
**Pull request by rohithdv**
This PR fixes #1544 . It changes the template files to add hyperlinks for missing request objects to REST APIs in the fybrik documentation. 
To test the changes locally, checkout this PR branch. Execute `make run ` in the `fybrik/site `folder and open link `http://127.0.0.1:8000/` in your browser. Then check the documentation to verify if the missing links are added. Thanks.  

/fixes #1544 

Signed-off-by: Rohith D Vallam <rovallam@in.ibm.com>

### CODE REVIEW

**Comment by roytman** [comment]
For all structs that contain `Details ResourceDetails`, the web pages  have entry `details  Details` (the type is wrong.), the link to `ResourceDetails` is broken. 

All entries whose type is defined in taxonomy, for example `GetAssetRequest.AssetID`, have empty description.

**Comment by rohithdv** [comment]
> For all structs that contain `Details ResourceDetails`, the web pages have entry `details Details` (the type is wrong.), the link to `ResourceDetails` is broken.
> 
> All entries whose type is defined in taxonomy, for example `GetAssetRequest.AssetID`, have empty description.


> For all structs that contain `Details ResourceDetails`, the web pages have entry `details Details` (the type is wrong.), the link to `ResourceDetails` is broken.
> 
> All entries whose type is defined in taxonomy, for example `GetAssetRequest.AssetID`, have empty description.


> For all structs that contain `Details ResourceDetails`, the web pages have entry `details Details` (the type is wrong.), the link to `ResourceDetails` is broken.
> 
> All entries whose type is defined in taxonomy, for example `GetAssetRequest.AssetID`, have empty description.


Fixed. Please check. Thanks.

**Comment by roytman** [comment]
@rohithdv , now it looks much better, thanks. 

However, some of the fields still do not have descriptions, e.g. `CreateAssetRequest.details`, `CreateAssetRequest.resourceMetadata`, `GetAssetRequest.OperationType` and others. 

Could you please take a look ?

**Comment by rohithdv** [comment]
> @rohithdv , now it looks much better, thanks.
> 
> However, some of the fields still do not have descriptions, e.g. `CreateAssetRequest.details`, `CreateAssetRequest.resourceMetadata`, `GetAssetRequest.OperationType` and others.
> 
> Could you please take a look ?



> @rohithdv , now it looks much better, thanks.
> 
> However, some of the fields still do not have descriptions, e.g. `CreateAssetRequest.details`, `CreateAssetRequest.resourceMetadata`, `GetAssetRequest.OperationType` and others.
> 
> Could you please take a look ?


`GetAssetRequest.OperationType` is basically an `enum` string. There is some issue regarding `enums` during doc generation. Currently we were following the approach suggested [here in Section The Right Way](https://github.com/kubernetes-sigs/kubebuilder/issues/1071). However the documentation is not generating properly with this approach. I have now changed to the approach provided [here in Section Alternative One](https://github.com/kubernetes-sigs/kubebuilder/issues/1071). In this approach, `GetAssetRequest.OperationType` is basically viewed as a string and hence there is no model file generated for this type. 
This required some changes to the place where we [put the comments](https://github.com/rohithdv/fybrik/blob/e57eb7643f8a94ab812cb421d789283a3629112c/pkg/model/datacatalog/model.go#L8) and the [kubebuilder validation](https://github.com/rohithdv/fybrik/blob/e57eb7643f8a94ab812cb421d789283a3629112c/pkg/model/datacatalog/api.go#L12). 
Please let me know if this approach is ok or should we revert back to old approach (in which case the documentation may not be properly generated). 

For non-primitive types like `CreateAssetRequest.details`, `CreateAssetRequest.resourceMetadata`, somehow the description fields are not working. I tried many ways to change the mustache file but the {{description }} field is coming out empty whenever there is a non-primite type involved. However, if you click on the hyperlink for  `CreateAssetRequest.details`, `CreateAssetRequest.resourceMetadata` or any other non-primitive type, the documentation of the description and all other fields will be provided in a new page. 
I think these are some limitations of the documentation generation for markdown using openapi-generator-cli tool. 
Please suggest if you are aware of any other ways to improve these aspects of the documentation. Thanks!

**Comment by shlomitk1** [comment]
@rohithdv Please look at the lines https://github.com/rohithdv/fybrik/blob/e57eb7643f8a94ab812cb421d789283a3629112c/pkg/model/taxonomy/infrastructure.go#L18-L28
This has correctly generated the validation of enums:
https://github.com/fybrik/fybrik/blob/d8c3a3977bf2a410bafd7b62d6ce98bbdffee8a0/charts/fybrik/files/taxonomy/taxonomy.json#L129-L137

**Review by shlomitk1 — APPROVED** [review]

**Pull request merged**
